name: TeXtidote Action
on:
  push:
    paths:
      - "/doc"
jobs:
  lint_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Lint LaTeX document
        uses: ChiefGokhlayeh/textidote-action@v5.2.0
        id: lint
        with:
          root_file: project.tex
          working_directory: doc/text/
          args: --check es

      - name: Upload TeXtidote report
        uses: actions/upload-artifact@v2
        with:
          name: textidote_report
          path: doc/text/report.html
      - name: Throw error if linter warnings exist
        if: ${{ steps.lint.outputs.num_warnings != 0 }}
        run: 'echo "::error file=project.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
