name: TeXtidote Action
on:
  pull_request:
env:
  IGNORED_RULES: sh:seclen,sh:stacked,sh:nobreak,sh:nonp
  IGNORES_ENVS: otherlanguage,displaymath
  IGNORED_MACROS: tableofcontents,listoffigures,listoftables,begin,centeroffset,oddsidemargin,evensidemargin,centering,bfseries,end,cleardoublepage,setlength,texttt
  DICT: ../words-allowlist.txt

jobs:
  lint_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: dict
      - run: 'echo $DICT'
      - name: Lint LaTeX document
        uses: ChiefGokhlayeh/textidote-action@v5
        id: lint
        with:
          root_file: proyecto.tex
          working_directory: doc/
          args: --check es --ignore $IGNORED_RULES --remove $IGNORES_ENVS --remove-macros $IGNORED_MACROS --dict $DICT

      - name: Upload TeXtidote report
        uses: actions/upload-artifact@v3
        with:
          name: textidote_report
          path: doc/report.html
      - name: Throw error if linter warnings exist
        if: ${{ steps.lint.outputs.num_warnings != 0 }}
        run: 'echo "::warning file=project.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
