name: checkTemplate
on:
  pull_request:
    types: [opened,edited]
    paths: 
      - "doc/"


jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobaciones sobre el cuerpo del PR
        uses: actions/github-script@v6
        env:
          GENERAR_PDF: false
          AVANZAR_DOC: false
        with:
          script: |
            const checklist = /\s*[-\*]\s+\[\s*([xX]?)\s*\]\s+([\w áéíóú]*):?/gm
            const body = context.payload.pull_request.body
            let match = checklist.exec(body)
            if (match != null) {
              let value = match[1] ? true : false
              if ( value === false ) {
                  core.warning("⚠️ No has marcado " + match[2] + " ⚠") 
              }else{
                if(match[2] === "Generar pdf"){
                  
                }
              }
              match = checklist.exec(body)
            }else{
              core.setFailed("❌ Por favor, usa la plantilla proporcionada." )
            }
