name: Check template
on:
  pull_request:
    types: [opened,edited]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobaciones sobre el cuerpo del PR
        id: checklist
        uses: JJ/pull-request-checks-action@v3
      - name: EVAL
        run: 'echo ${{ steps.checklist.outputs.AVANZAR }} && ${{ steps.checklist.outputs.AVANZAR == false}} && ${{ steps.checklist.outputs.AVANZAR == true}}'
      - name: Aborta si no avanza
        if: ${{ steps.checklist.outputs.AVANZAR }} == false
        run: echo "Redacta lo hecho en este PR antes de continuar al siguiente." && exit 1