name: checkTemplate
on:
  pull_request:
    types: [opened,edited]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobaciones sobre el cuerpo del PR
        id: checklist
        uses: JJ/pull-request-checks-action@v3
      #- name: Generar PDF
        # if: ${{ steps.checklist.outputs.GENERAR == false }}
       # run: echo FALSE
#        uses: xu-cheng/latex-action@v2
#        with:
#          working_directory: doc/
#          root_file: text/project.tex
      - name: GENERAR_CHECK1
        if: $GENERAR != null
        run: echo $GENERAR "existe"
      - name: AVANZAR_CHECK1
        if: $AVANZAR != null
        run: echo $AVANZAR "existe"
      - name: GENERAR_CHECK2
        if: $GENERAR == null
        run: echo $GENERAR "NO existe"
      - name: AVANZAR_CHECK2
        if: $AVANZAR == null
        run: echo $AVANZAR "NO existe"

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          path: project.pdf
