name: checkTemplate
on:
  pull_request:
    types: [opened,edited]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobaciones sobre el cuerpo del PR
        uses: actions/github-script@v6
        id: checklist
        with:
          script: |
            const checklist = /\s*[-\*]\s+\[\s*([xX]?)\s*\]\s+([\w áéíóú]*):?/gm
            const body = context.payload.pull_request.body
            let checkDict = {}
            let match = checklist.exec(body)
            if (match != null){
              core.setFailed("❌ Por favor, usa la plantilla proporcionada." )
            }
            while (match != null) {
              let value = match[1] ? true : false
              if ( value === false ) {
                  core.warning("⚠️ No has marcado " + match[2] + " ⚠") 
              }
              dict[match[2]] = value
              }
              match = checklist.exec(body)
            }
            return dict
          run: 'echo "${{ steps.checklist }}"; exit 0;'
