name: Se han hecho las tareas previas al PR
on:
  pull_request:
    types: [opened,edited]
    paths: 
      - "doc/"

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobaciones sobre el cuerpo del PR
        uses: actions/github-script@v6
        with:
          script: |
            const checklist = /\s*[-\*]\s+\[\s*([xX]?)\s*\]\s+([\w ]*):?/gm
            const body = context.payload.pull_request.body
            core.notice(body)
            let match = checklist.exec(body)
            core.notice(match)
            let warned = false
            while (match != null) {
              core.notice("Match 1" + match[1])
              core.notice("Match entero" + match)
              let value = match[1] ? true : false
              if ( value === false ) {
                  core.setFailed("⚠️ No has marcado " + match[2] + " ⚠") 
                  if ( !warned ) {
                      core.warning("👉 Es importante que sigáis la lista de comprobación en cada entrega" )
                      warned = true
                  }
              }
              match = checklist.exec(body)
            }
