name: checkTemplate
on:
  pull_request:
    types: [opened,edited]

jobs:
  get-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobaciones sobre el cuerpo del PR
        id: checklist
        uses: JJ/pull-request-checks-action@v3
      - name: Generar PDF
        uses: xu-cheng/latex-action@v2
        if: ${{steps.checklist.outputs.GENERAR}}
        with:
          working_directory: doc/
          root_file: text/project.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          path: main.pdf
