name: llamador

on:
  pull_request:
    types: [opened,edited]

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/testAction.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
